#!/bin/bash

CACHE_FILE="$HOME/.cache/git-dirs"

STDOUT=0

# handle mutliple commandline flags -f -h and -c
while getopts ":fhs" opt; do
  case $opt in
    f)
      rm "$CACHE_FILE"
      ;;
    h)
      echo "Usage: fzf_open_code [-f] [-h] [-c]"
      echo "  -f: force refresh of cache file"
      echo "  -h: show this help message"
      echo "  -s: pass to stdout instead of opening in vscode"
      exit 0
      ;;
    s)
      STDOUT=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

if [[ -f "$CACHE_FILE" && $(find "$CACHE_FILE" -mmin -60) ]]; then
  DIRS=$(cat "$CACHE_FILE")
else
  DIRS=$(find ~/dev -type d -name '.git' -printf '%h\n' )
  echo "$DIRS" > "$CACHE_FILE"
fi

DIR=$(echo "$DIRS" | fzf)

# If dir is empty exit
if [[ -z "$DIR" ]]; then
  exit 0
fi

if [[ $STDOUT -eq 1 ]]; then
  echo "$DIR"
  exit 0
fi

# if dir contains devcontainer.json open in devcontainer else vscode
if [[ -f "$DIR/.devcontainer/devcontainer.json" ]]; then
  devcontainer open "$DIR"
else
  code "$DIR"
fi
