#!/bin/bash
if ! command -v wslvar &> /dev/null
then
    echo "wslvar could not be found. Installing Wslu"
    sudo apt-get install wslu -y
fi
WIN_PATH=$(wslpath "$(wslvar USERPROFILE)")
echo Copying .ssh from $WIN_PATH
cp -r ${WIN_PATH}/.ssh ~

PUB_KEYS=$(find ~/.ssh -name "*.pub")
PRIVKEYS=$(echo $PUB_KEYS | sed -r -e "s~(.*)\.pub~\1~g")
for KEY in $PUB_KEYS; do
    if [ -f $KEY ]; then
        echo Fixing permissions on $KEY
        chmod 644 $KEY
    fi
done

for KEY in $PRIVKEYS; do
    if [ -f $KEY ]; then
        echo Fixing permissions on $KEY
        chmod 600 $KEY*
    fi
done
